### ISSUE TITLE
commands.js value

### ISSUE THREAD

**Issue by elgibor-solution** [geryb-bg/webusb#1]
Hi Gery,

I try your code with digital percona u.are.u 4500 fingerprint scanner.

Can you advice how to get the value inside the commands.js?

**Comment by geryb-bg** [comment]
Hey

Those values are very specific to the brand of fingerprint reader that you use. I found another implementation for the one I used that was in Java and got the values out of there (https://github.com/shawnsarwar/OpenANDID).

If you can't find it anywhere, what you could do is use something like Wireshark. You would have to install the actual drivers for the fingerprint reader, run Wireshark and record all of the interactions between the fingerprint reader and your computer.

Just one thing with Wireshark is that it only gives access to USB devices if you are using Windows, it won't work on Mac or Linux (this is why I struggled).

Hope this helps :)
